language: node_js
node_js:
- node
branches:
  only:
  - master
script:
- npm run deploy
deploy:
  provider: script
  script: ./travis-deploy-pages
  on:
    branch: master
  skip_cleanup: true
env:
  global:
    secure: RBz6KCjxhltRg1hWywgtQSCkaSiNwl6zo0qoYHDEZrv0GcwH9HrWM5aUeUAAdDSIqau7pKFu3K43XqyevY0vSdV3QbLI54ILtm13BmpJCZGw9L9bF1gBTV3tLanUkaU+MmNeHwzyp69ErjcS+cLhhrU0miaFjzvS5SoVDum75Xh0zQmmFcb7UgodV/wStXfzEyQAMSZPy/Q9f4+wbFa47UCsvAwtftG6S2zr1X3HtEZxxuOdwATirnnxNPEctrbvxSAmTifBH6laQ7SztzRLbbOzVCy5q9vvj1tcsN7i9orRrOLEWFaDMbeDiwyYZVKseOLOJOiSpEQa/5A2nVWm3tJnavmxC/E/cu4GRxGN2kYk9kB0GEzo0r9Gar8zmcgBe7omuQL7BaNh9KirJqH1++Ok8pEzDs0taGDpISY4KEPKiOeYNVB+HlHit/ZkBfXZATtcxI9ytu64QLhwZgivWxFg8CbsvhNjDnl91GOlq2pR0dFXLVjXIb8uQF8zJwopL+dLr6yc3Ke/GUplelwGHPh6tRLf35z2MFpyvz1zyFcOXfyVfqOUAfyIFfrISjSRDc4p+UQgy5Ogqq6pmqmtfx+kBVkiqyRcc9TZx5XkLa/OV6Xw/IUkRMROJKD212mHMm3x4icK64RxsOakmsDl8YoMxCrfp6MHvTSoo+q0W7M=
