language: node_js
node_js:
- node
branches:
  only:
  - master
script:
- npm run deploy
deploy:
  provider: script
  script: ./travis-deploy-pages
  on:
    branch: master
  skip_cleanup: true
env:
  global:
    secure: jhRybEMR1JM45xtxnQaAryFA54XNAOZTS0Ib0rj0Zvpl4K8Mxitp0ylu6xJHZOG66GLF8M160feuY7FykOwrAjQyBiBFobOtmrIv0ldRPsqSAxPo4Cz1FcFm2Iu/X9W2HGcdPvJ3qOWKCrRs94U+F+Ayw2peG08eSHc19jp3qMdl5AOJ6anFwSp0tNHKOgpoVpKOwMD/60+PntkNDCBdPKvbiyVM0yneN8HlubepGZly/lulUBlQLYVgGwI2YBEkLkK9FdTq0JK3WEJf4JINDIOzoLyZyGBm+nmj97aaQqiY1zudLQ2XyLpmcDt96kW7oAZerOa4vtoG0JL8/uschwMzE7QFuKOBPE6R/CE20u89cyWg4998vbHBr7mSJvqW3RwxYe1nYxZ+xzVj8PBX+Pg/XPDWxq6hCb77qTZtg9AvPEICuPel44DWmypDsCJgXZt79K/0o0PqYTyZubVO7F5UO3Gb8RmPDHkYDEYiIs41wInR5CKWJQZCzvXCDT+yWIjtkXomgm2xyWgD4XsHsg59C4HNNlFBRC0FTgkWB46GoutYdDWpEabf9UxEpW5hMHiGJ4WXscNoPS8pEtVCWvw53hsQ8yGUHAXQIgSBeH3zGzrOkCFsJNurW9muFn3JN46LwPoHikCuEadeTzIEcT47/ggXAFUFF04sKtZmzNI=
